#+TITLE:       Jon-Michael Deldin's Emacs Configuration
#+STARTUP:     align hidestars indent
#+STYLE: <style>html { font: 14px Helvetica, sans-serif } body { width: 85%; margin: 2% auto;} pre, code { font-family: Monaco, Consolas, 'Bitstream Vera Sans', monospace; }</style>

I started using Emacs in the fall of 2010 after a few years of Vim. I
use GNU Emacs 25.1+ on Ubuntu for Org-Mode, Ruby, LaTeX, sh, and a host
of miscellaneous other languages.

* Installation
You can clone directly as =$HOME/.emacs.d=:

#+BEGIN_SRC sh
  git clone git://github.com/jmdeldin/.emacs.d.git ~/.emacs.d/
#+END_SRC

* Notes
** Improvements
*** TODO add org-mode/orgstruct to magit
*** TODO evaluate company-mode
** Keys
| Key         | Description                                     |
|-------------+-------------------------------------------------|
| C-q TAB     | Insert literal tab                              |
| M-y         | Traverse kill-ring (after C-y)                  |
| C-u C-SPC   | Jump to last mark                               |
| M-n         | (In =cua-mode=) Increment digit                 |
| C-M \       | Indent according to major mode                  |
| C-c C-s     | Start IRB                                       |
| C-c C-r     | Send region to IRB (C-c C-s first)              |
| C-x v =     | Diff against HEAD                               |
| C-u C-x v = | Diff against other branch                       |
| C-x v u     | Discard changes                                 |
| C-x v ~     | Checkout another rev                            |
| C-x v l     | View commit log                                 |
| C-Shift BS  | Kill whole line                                 |
| C-c '       | Edit code block (org-babel)                     |
| C-x r m     | Bookmark the current loc in a file              |
| C-x r b     | Jump to bookmark                                |
| C-x r l     | List bookmarks                                  |
| C-x C-n     | Narrow region                                   |
| C-x C-w     | Widen region                                    |
| C-x r w     | Save window configuration                       |
| C-x r j     | Restore configuration                           |
| M-&         | Execute shell command asynchronously            |
| C-x r t     | Removes the content in a rectangle (mark first) |
| M-0 .. M-9  | Prefix argument                                 |
| M-- M-c     | Capitalize last word (M-dash for back)          |
| M-e         | Forward sentence                                |
| M-a         | Backward sentence                               |
| C-M-f       | Move forward by a balanced expr (e.g., ",', []) |
| C-M-b       | Move backward by a balanced expr                |
| M-m         | back-to-indentation (^ in Vim)                  |
| M-r         | move the point w/o scrolling                    |
| M-g M-g     | goto-line                                       |
| M-o M-s     | Center text                                     |
| C-x r N     | Number lines                                    |

** Searching
| Key     | Description                               |
|---------+-------------------------------------------|
| M-p     | previous search term                      |
| M-n     | next search term                          |
| M-c     | toggle case-sensitivity                   |
| C-s C-w | search with the word at point (* inv Vim) |

** Ido-mode
These keys work inside the Ido minibuffer (C-x C-f).

| Key       | Description                                           |
|-----------+-------------------------------------------------------|
| C-d       | Open a dired buffer in the current directory          |
| C-a       | Toggles showing ignored files                         |
| C-c       | Toggles case-sensitivity                              |
| C-s & C-r | Move to the next/prev match                           |
| C-SPC     | Restrict to an expr (C-x C-b .org C-SPC for just org) |

** Functions and modes
| Function               | Description                           |
|------------------------+---------------------------------------|
| follow-mode            | Browse splits like they're one window |
| ielm-mode              | Elisp REPL                            |
| hexl-mode              | Hex viewer                            |
| bury-buffer            | Send buffer to end of list            |
| highlight-changes-mode | Show newly changed text in red        |
| info-apropos           | full-text search of info              |

** org-mode
| Command     | Decription                                 |
|-------------+--------------------------------------------|
| C-c C-n     | next heading                               |
| C-c C-p     | previous heading                           |
| C-c C-f     | next heading (same level)                  |
| C-c C-b     | previous heading (same level)              |
| C-c C-u     | back to a higher heading                   |
| C-c /       | Sparse tree                                |
| M-S-RET     | Insert new item with checkbox              |
| M-S-UP/DOWN | Move items including subitems up/down      |
| C-c -       | Cycle list level through different bullets |

** Dired
| Command | Description        |
|---------+--------------------|
| % u     | uppercase filename |
| % l     | lowercase filename |
| % R     | regex rename       |

* Initialization
** Load custom helper functions
#+BEGIN_SRC emacs-lisp
  (load-file (concat user-emacs-directory "site-lisp/defuns.el"))
#+END_SRC

** Set =custom-file=
On clean installs, some packages will try to append custom vars to
init.el, breaking installation. The =custom-file= must be set before
trying to install packages.
#+BEGIN_SRC emacs-lisp
  (setq custom-file (concat user-emacs-directory "local/emacs-custom.el"))
  (load custom-file 'noerror)
#+END_SRC

** Set up repositories
#+BEGIN_SRC emacs-lisp
  (setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                           ("melpa-stable" . "https://stable.melpa.org/packages/")
                           ("melpa-unstable" . "https://melpa.org/packages/")))
#+END_SRC

** Define required packages
We can declare the origin of our packages with the
=package-pinned-packages= variable:
#+BEGIN_SRC emacs-lisp
  (setq package-pinned-packages
        '(
          (ace-window . "melpa-stable")
          (ag   . "melpa-stable")
          (alchemist . "melpa-stable")
          (cider . "melpa-stable")
          (clojure-mode . "melpa-stable")
          (coffee-mode . "melpa-stable")
          (dim . "melpa-unstable")
          (elfeed . "melpa-unstable")
          (evil . "melpa-unstable")
          (evil-matchit . "melpa-stable")
          (evil-numbers . "melpa-stable")
          (evil-paredit . "melpa-unstable")
          (geiser . "melpa-stable")
          (go-mode . "melpa-stable")
          (haml-mode . "melpa-stable")
          (htmlize . "melpa-unstable") ; for org exports
          (magit . "melpa-stable")
          (markdown-mode . "melpa-stable")
          (nginx-mode . "melpa-stable")
          (org . "gnu")
          (projectile . "melpa-stable")
          (rainbow-mode . "gnu")
          (rspec-mode . "melpa-stable")
          (smex . "melpa-stable")
          (tiny . "melpa-unstable") ; for invoices
          (tuareg . "melpa-stable")
          (use-package . "melpa-stable") ; until bundled with Emacs
          (yaml-mode . "melpa-stable")
          ))
#+END_SRC

** Install Packages
#+BEGIN_SRC emacs-lisp
  (setq jm/packages (mapcar 'car package-pinned-packages))

  (jm/install-all-packages jm/packages)
  (setq use-package-verbose t)
#+END_SRC

** Server
Only load the server if it isn't running:
#+BEGIN_SRC emacs-lisp
  (load "server")
  (unless (server-running-p)
    (server-start))
#+END_SRC

* Garbage
This section is dedicated to all of the turd files Emacs leaves all over
your machine.

** Lockfiles
Disable lockfiles -- there's only one user on this machine. This prevents
[[https://github.com/guard/guard][guard]] from re-running specs everytime the file is edited (but not saved).
#+BEGIN_SRC emacs-lisp
  (setq create-lockfiles nil)
#+END_SRC

** Backups
Place backups in =~/.emacs.d/local/backups=:
#+BEGIN_SRC emacs-lisp
  (setq backup-by-copying t)
  (setq backup-directory-alist
        (list (cons "." (jm/local-path "backups"))))
  (setq delete-old-versions t)
  (setq kept-new-versions 6)
  (setq kept-old-versions 2)
  (setq version-control t)
#+END_SRC

** Auto-saves
Keep auto-save files together. Test with =M-x do-auto-save=.
#+BEGIN_SRC emacs-lisp
  (let ((new-dir (jm/local-path "auto-saves/")))
    (setq auto-save-list-file-prefix new-dir)
    (setq auto-save-file-name-transforms
        `((".*" ,new-dir t))))
#+END_SRC

** Bookmarks
Use =~/.emacs.d/local/.emacs.bmk= for bookmarks:
#+BEGIN_SRC emacs-lisp
  (setq bookmark-file (jm/local-path "bookmarks"))
#+END_SRC

* Communication
** ERC
Prevent auto-joining =#erc=
#+BEGIN_SRC emacs-lisp
  (setq erc-autojoin-channels-alist '())
#+END_SRC

Spell-check ERC:
#+BEGIN_SRC emacs-lisp
  (erc-spelling-mode 1)
#+END_SRC

Ignore noise:
#+BEGIN_SRC emacs-lisp
  (setq erc-network-hide-list '("JOIN" "PART" "QUIT" "NICK" "MODE"))
  (setq erc-track-exclude-server-buffer t)
#+END_SRC

Highlight nick:
#+BEGIN_SRC emacs-lisp
  (setq erc-current-nick-highlight-type 'nick)
#+END_SRC

** mu4e
*** Initialization
Run this in your =local/local.el= file to actually initialize mu4e. I
keep this in a function for the machines I don't use mu4e on.

#+BEGIN_SRC emacs-lisp
  (defun jm/setup-mu4e ()
    (add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e/")
    (require 'mu4e)
    (require 'mu4e-contrib))
#+END_SRC

*** Network
I use =nullmailer= locally for SMTP, which acts just like sendmail:
#+BEGIN_SRC emacs-lisp
  (setq message-send-mail-function 'message-send-mail-with-sendmail)
#+END_SRC

=getmail= is a pretty simple client to configure:
#+BEGIN_SRC emacs-lisp
  (setq mu4e-get-mail-command "getmail")
#+END_SRC

*** Reading
Enable inline-images:
#+BEGIN_SRC emacs-lisp
  (setq mu4e-view-show-images t)
#+END_SRC

Use imagemagick to convert a file when necessary:
#+BEGIN_SRC emacs-lisp
  (when (fboundp 'imagemagick-register-types)
    (imagemagick-register-types))
#+END_SRC

Convert HTML emails:
#+BEGIN_SRC emacs-lisp
(setq mu4e-html2text-command 'mu4e-shr2text)
#+END_SRC

View in browser:
#+BEGIN_SRC emacs-lisp
  ; (add-to-list 'mu4e-view-actions '("ViewInBrowser" . mu4e-action-view-in-browser) t)
#+END_SRC
*** Writing
Don't reply to yourself:
#+BEGIN_SRC emacs-lisp
  (setq mu4e-compose-dont-reply-to-self t)
#+END_SRC

Close the compose buffer after sending:
#+BEGIN_SRC emacs-lisp
  (setq message-kill-buffer-on-exit t)
#+END_SRC

One last chance to undo:
#+BEGIN_SRC emacs-lisp
  (add-hook 'message-send-hook
    (lambda ()
      (unless (yes-or-no-p "Are you sure you want to send this?")
        (signal 'quit nil))))
#+END_SRC

*** Keybindings
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "<f8>") 'mu4e)
#+END_SRC

* News
Elfeed is a really nice RSS reader for Emacs that's easy to use and
fast.

** Elfeed Configuration
Keep the database inside =~/.emacs.d= instead of in =$HOME=:
#+BEGIN_SRC emacs-lisp
  (setq elfeed-db-directory (concat user-emacs-directory "local/elfeed"))
#+END_SRC

Keybinding:
#+BEGIN_SRC emacs-lisp
  (defun jm/elfeed ()
    "Download feed updates before using elfeed."
    (interactive)
    (elfeed-update)
    (elfeed))

  (global-set-key (kbd "<f9>") 'jm/elfeed)
#+END_SRC

** Feeds
#+BEGIN_SRC emacs-lisp
  (setq elfeed-feeds
        '(
          ("https://feeds.feedburner.com/lifehacker/full" drivel)
          ("http://nullprogram.com/feed/" emacs)
          ("http://planet.emacsen.org/atom.xml" emacs)
          ("http://sachachua.com/blog/feed/" emacs)
          ("https://www.masteringemacs.org/feed" emacs)
          ("https://www.reddit.com/r/emacs.xml" emacs)
          ("http://matthewkirk.com/feed/" friends)
          ("https://www.reddit.com/r/linux.rss" linux)
          ("http://www.jmdeldin.com/atom.xml" personal)
          ("https://jvns.ca/atom.xml" programming)
          ("https://www.reddit.com/r/everett.xml" news)))
#+END_SRC

* Text Editing
Default to 72 column width for plain text
#+BEGIN_SRC emacs-lisp
  (add-hook 'text-mode-hook
            '(lambda ()
               (set-fill-column 72)))
#+END_SRC

Match parens and quotes
#+BEGIN_SRC emacs-lisp
  (electric-pair-mode t)
#+END_SRC

Enable on-the-fly reindentation
#+BEGIN_SRC emacs-lisp
  (electric-indent-mode t)
#+END_SRC

Insert a newline around special characters
#+BEGIN_SRC emacs-lisp
  (electric-layout-mode t)
#+END_SRC

Use single spaces between sentences for =fill-paragraph= (=M-q=)
#+BEGIN_SRC emacs-lisp
  (setq sentence-end-double-space nil)
#+END_SRC

Use Unicode everywhere, as per [[https://www.masteringemacs.org/article/working-coding-systems-unicode-emacs][Mastering Emacs' post]]:

#+BEGIN_SRC emacs-lisp
  (set-language-environment "UTF-8")
  (prefer-coding-system 'utf-8)
  (set-default-coding-systems 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (setq-default buffer-file-coding-system 'utf-8)

  ;; clipboard as UTF-8
  (setq x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING))
#+END_SRC

Changing a region's case is useful
#+BEGIN_SRC emacs-lisp
  (put 'upcase-region 'disabled nil)
  (put 'downcase-region 'disabled nil)
#+END_SRC

Remember last edit position
#+BEGIN_SRC emacs-lisp
  (require 'saveplace)
  (setq-default save-place t)
  (setq save-place-file (jm/local-path "places"))
#+END_SRC

** Auto-Complete Mode
#+BEGIN_SRC emacs-lisp
  (use-package auto-complete-config
    :ensure auto-complete
    :pin melpa-stable
    :defer 2
    :diminish auto-complete-mode
    :config
    (ac-config-default)
    (ac-flyspell-workaround)
    (setq ac-ignore-case nil)
    (setq ac-comphist-file (jm/local-path "ac-comphist.dat")))

  (use-package org-ac
    :ensure t
    :defer 2
    :pin melpa-stable
    :config (org-ac/config-default))
#+END_SRC

** Spelling
Use =aspell= instead of =ispell=, use =list= for faster region checking, and
use a faster suggestion mode.

#+BEGIN_SRC emacs-lisp
  (setq ispell-program-name "aspell")
  (setq ispell-list-command "list")
  (setq ispell-extra-args '("--sug-mode=ultra"))
#+END_SRC

Turn it on for some modes:
#+BEGIN_SRC emacs-lisp
  (mapcar (lambda (mode)
            (add-hook mode (lambda () (flyspell-mode t))))
          '(org-mode-hook markdown-mode text-mode))
  (add-hook 'git-commit-mode-hook 'turn-on-flyspell)
#+END_SRC

** Whitespace
Wrap lines at column 78
#+BEGIN_SRC emacs-lisp
  (setq-default fill-column 78)
#+END_SRC

Highlight right-margin when whitespace-mode is on
#+BEGIN_SRC emacs-lisp
  (setq whitespace-line-column fill-column)
#+END_SRC

Highlight empty lines
#+BEGIN_SRC emacs-lisp
  (setq-default indicate-empty-lines t)
#+END_SRC

Hard-wrap lines all the time
#+BEGIN_SRC emacs-lisp
  (add-hook 'text-mode-hook 'turn-on-auto-fill)
#+END_SRC

Use spaces, not tabs (C-q C-i to insert a hard-tab)
#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
#+END_SRC

2-space tabs
#+BEGIN_SRC emacs-lisp
  (setq-default tab-width 2)
#+END_SRC

Insert tabs when appropriate
#+BEGIN_SRC emacs-lisp
  (setq indent-line-function 'insert-tab)
#+END_SRC

Insert a newline at the EOF
#+BEGIN_SRC emacs-lisp
  (setq-default require-final-newline t)
#+END_SRC

Delete trailing whitespace on save
#+BEGIN_SRC emacs-lisp
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC

** Highlight Stuff
#+BEGIN_SRC emacs-lisp
  (use-package highlight-indent-guides
    :ensure t
    :pin melpa-unstable
    :config
    (setq highlight-indent-guides-method 'fill)
    (mapcar (lambda (hook) (add-hook hook 'highlight-indent-guides-mode))
            '(prog-mode-hook yaml-mode-hook)))
#+END_SRC

* UI
Hide the {menu,tool,scroll}bars
#+BEGIN_SRC emacs-lisp
  (if window-system
      (progn
        (scroll-bar-mode -1)
        (tool-bar-mode -1)))
  (menu-bar-mode -1)
#+END_SRC

Hide the startup messages
#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-message t)
  (setq inhibit-startup-echo-area-message t)
#+END_SRC

"y or n" instead of "yes or no"
#+BEGIN_SRC emacs-lisp
  (fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

Show line & column number in the mode line
#+BEGIN_SRC emacs-lisp
  (column-number-mode t)
#+END_SRC

Show file size
#+BEGIN_SRC emacs-lisp
  (size-indication-mode t)
#+END_SRC

Highlight parens
#+BEGIN_SRC emacs-lisp
  (show-paren-mode t)
  (setq show-paren-delay 0.0)
#+END_SRC

Highlight current line
#+BEGIN_SRC emacs-lisp
  (global-hl-line-mode 1)
#+END_SRC

Use =ibuffer= instead of =list-buffers=
#+BEGIN_SRC emacs-lisp
  (defalias 'list-buffers 'ibuffer)
#+END_SRC

No bells
#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function 'ignore)
#+END_SRC

** Window Management
Restore window configuration with =C-c LEFT=
#+BEGIN_SRC emacs-lisp
  (winner-mode)
#+END_SRC

Enable windmove -- default binding is shift
#+BEGIN_SRC emacs-lisp
  (windmove-default-keybindings)
  (setq windmove-wrap-around t)
#+END_SRC

Make windmove work in org-mode:
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-shiftup-final-hook 'windmove-up)
  (add-hook 'org-shiftleft-final-hook 'windmove-left)
  (add-hook 'org-shiftdown-final-hook 'windmove-down)
  (add-hook 'org-shiftright-final-hook 'windmove-right)
#+END_SRC

** Minibuffer
*** IDO
Interactively-do-things is the greatest Emacs extension.

#+BEGIN_SRC emacs-lisp
  (setq ido-enable-flex-matching t)
  (setq ido-everywhere t)
  (setq ido-show-dot-for-dired t)
  (setq ido-save-directory-list-file (jm/local-path "ido.last"))
  (setq ido-use-virtual-buffers t)
  (ido-mode 1)
#+END_SRC
**** Uniquify
Use part of the directory to distinguish between identically-named files:
#+BEGIN_SRC emacs-lisp
  (require 'uniquify)
  (setq uniquify-buffer-name-style 'forward)
#+END_SRC
**** Minibuffer History
Save minibuffer history:
#+BEGIN_SRC emacs-lisp
  (savehist-mode 1)
  (setq savehist-additional-variables '(kill-ring search-ring regexp-search-ring))
  (setq savehist-file (jm/local-path "savehist"))
#+END_SRC
**** Recent Files
Enable recent files:
#+BEGIN_SRC emacs-lisp
  (require 'recentf)
  (setq recentf-save-file (jm/local-path "recentf"))
  (setq recentf-max-saved-items 1000)
  (recentf-mode 1)
#+END_SRC

** Mouse
Enable mouse support in a terminal (from [[http://stackoverflow.com/a/8859057/73492][StackOverflow]]):

#+BEGIN_SRC emacs-lisp
  (unless window-system
    (require 'mouse)
    (xterm-mouse-mode t)
    (global-set-key [mouse-4] '(lambda ()
                                 (interactive)
                                 (scroll-down 1)))
    (global-set-key [mouse-5] '(lambda ()
                                 (interactive)
                                 (scroll-up 1)))
    (defun track-mouse (e))
    (setq mouse-sel-mode t))
#+END_SRC

** Keybindings
*** Evil
Arguably the best Vim ever, but sometimes, I still want Emacs keys.
#+BEGIN_SRC emacs-lisp
(evil-mode t)
(define-key evil-insert-state-map (kbd "C-a") 'beginning-of-line)
(define-key evil-insert-state-map (kbd "C-e") 'end-of-line)
(define-key evil-insert-state-map (kbd "C-d") 'delete-forward-char)
(define-key evil-insert-state-map (kbd "C-k") 'kill-line)
(define-key evil-normal-state-map (kbd "C-p") 'evil-previous-line)
(define-key evil-normal-state-map (kbd "C-n") 'evil-next-line)
(define-key evil-insert-state-map (kbd "C-p") 'evil-previous-line)
(define-key evil-insert-state-map (kbd "C-n") 'evil-next-line)
(define-key evil-insert-state-map (kbd "C-z") 'suspend-emacs)
(define-key evil-normal-state-map (kbd "C-z") 'suspend-emacs)
#+END_SRC

Disable vi in some buffers:
#+BEGIN_SRC emacs-lisp
  (mapc (lambda (mode)
          (evil-set-initial-state mode 'emacs))
        '(elfeed-show-mode elfeed-search-mode Info-mode-hook Ledger-Report-Mode))
#+END_SRC

*** Editing
=M-/= -- use a more powerful expansion
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-/") 'hippie-expand)
#+END_SRC

=C-c C-r= -- Revert buffer
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c C-r") 'revert-buffer)
#+END_SRC

Swap =C-j= and =RET=
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "RET") 'reindent-then-newline-and-indent)
  (global-set-key (kbd "C-j") 'newline)
#+END_SRC

=C-c C-d= -- Remove trailing whitespace
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c C-d") 'delete-trailing-whitespace)
#+END_SRC

=C-w= -- delete the previous word (like most shells)
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-w") 'backward-kill-word)
#+END_SRC

C-x C-k -- kill region (since we just unbound it with C-w)
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x C-k") 'kill-region)
#+END_SRC

=C-x C-j= -- join line
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x C-j") 'join-line)
#+END_SRC

=C-c w= -- toggle whitespace mode
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c w") 'global-whitespace-mode)
#+END_SRC

better commenting (replaces the original comment-dwim)
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-;") 'comment-or-uncomment-region)
#+END_SRC

=C-x m= -- recompile
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x m") 'recompile)
#+END_SRC

=C-x g= -- =magit-status=
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x g") 'magit-status)
#+END_SRC

=C-x x= -- =jm/shell=
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x x") 'jm/shell)
#+END_SRC

=M-#= -- =jm/reload-init=
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-#") 'jm/reload-init)
#+END_SRC

=C-x a= -- =ag-regexp-project-at-point=
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x a") 'ag-regexp-project-at-point)
#+END_SRC

=C-x p= -- find files in project
#+BEGIN_SRC emacs-lisp
  (projectile-global-mode t)
  (setq projectile-known-projects-file (jm/local-path "projectile-bookmarks.eld"))
  (setq projectile-cache-file (jm/local-path "projectile-cache"))
  (global-set-key (kbd "C-x p") 'projectile-find-file)
#+END_SRC

=M-x= -- ido-like completion for functions
#+BEGIN_SRC emacs-lisp
  (smex-initialize)
  (global-set-key (kbd "M-x") 'smex)
  (setq smex-save-file (jm/local-path "smex-items"))
#+END_SRC

*** Windows
=M-s/M-S= -- switch windows
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-s") 'ace-window)
  (global-set-key (kbd "M-S") 'ace-window)
#+END_SRC

*** Mac
Make the Cmd and Opt keys work for =M-x=
#+BEGIN_SRC emacs-lisp
  (when system-type "darwin"
    (setq-default mac-command-modifier 'super)
    (setq-default mac-option-modifier 'meta))
#+END_SRC

** Clutter
Hide a bunch of minor modes:
#+BEGIN_SRC emacs-lisp
  (dim-minor-names '(
             (auto-fill-function "") ; the "Fill" text
             (eldoc-mode "")
             (flyspell-mode "")
             (org-indent-mode "")
             (projectile-mode "")
             (undo-tree-mode "")
             ))
#+END_SRC

VC mode does not need to show more than the branch. The following code
[[http://emacs.stackexchange.com/a/10957][from Malabrba]] does just that:
#+BEGIN_SRC emacs-lisp
  (setcdr (assq 'vc-mode mode-line-format)
          '((:eval (replace-regexp-in-string "^ Git" " " vc-mode))))
#+END_SRC

** Themes
For dumb terminals:
#+BEGIN_SRC emacs-lisp
  (if (and (not window-system) (string= (getenv "TERM") "dumb"))
      (progn
        (set-face-background 'hl-line "#666")
        (set-face-foreground 'hl-line "#fff")))
#+END_SRC

For GUIs:

#+BEGIN_SRC emacs-lisp
  (if window-system
      (let ((jm/font "Source Code Pro-13"))
        (set-face-attribute 'default nil :font jm/font)
        (set-frame-font jm/font)))
#+END_SRC

* Languages
** C
The only way to program.
#+BEGIN_SRC emacs-lisp
  (setq c-default-style "k&r")
#+END_SRC

Use four spaces for tabs.
#+BEGIN_SRC emacs-lisp
  (setq-default c-basic-offset 4)
#+END_SRC

Many-windows mode makes Emacs into a more traditional IDE for GDB. See
=C-h f gdb= for details. *NOTE:* This doesn't work on OS 10.8 (non-stop
mode isn't supported).

#+BEGIN_SRC emacs-lisp
  (setq gdb-many-windows t)
#+END_SRC

** Clojure
#+BEGIN_SRC emacs-lisp
  (add-hook 'cider-mode-hook 'cider-turn-on-eldoc-mode)
  (setq cider-repl-result-prefix ";; => ")
  (add-hook 'cider-repl-mode-hook 'subword-mode)
  (setq cider-auto-select-error-buffer nil)

  (add-hook 'cider-mode-hook
            (lambda ()
              (local-set-key (kbd "C-c ,") 'cider-test-run-tests)))

#+END_SRC

** CSS
Turn on =rainbow-mode= for colored hex values
#+BEGIN_SRC emacs-lisp
  (add-hook 'css-mode-hook 'rainbow-mode)
#+END_SRC

Prevent SCSS from compiling at save time:
#+BEGIN_SRC emacs-lisp
  (setq scss-compile-at-save nil)
#+END_SRC

Two spaces:
#+BEGIN_SRC emacs-lisp
  (setq css-indent-offset 2)
#+END_SRC

** Graphviz
#+BEGIN_SRC emacs-lisp
  (associate-file-type '(".gv" ".dot") 'graphviz-dot-mode)
#+END_SRC

** JavaScript
2 space indent:

#+BEGIN_SRC emacs-lisp
  (setq js-indent-level 2)
#+END_SRC

Support React stuff:
#+BEGIN_SRC emacs-lisp
  (associate-file-type '(".jsx") 'js-mode)
#+END_SRC

** LaTeX
Produce PDFs instead of DVIs
#+BEGIN_SRC emacs-lisp
  (setq TeX-PDF-mode t)
#+END_SRC

** Lisp
#+BEGIN_SRC emacs-lisp
  (define-key lisp-mode-shared-map (kbd "C-c e") 'eval-buffer)

  ; probably not needed with 25+ 4
  (add-hook 'emacs-lisp-mode-hook 'turn-on-eldoc-mode)
#+END_SRC

** Markdown
#+BEGIN_SRC emacs-lisp
  (associate-file-type '(".md" ".markdown") 'markdown-mode)
#+END_SRC

** ERB
Support editing mixed mode files, like ERB templates.

#+BEGIN_SRC emacs-lisp
  (use-package mmm-auto
    :ensure mmm-mode
    :pin melpa-stable
    :mode ((".html.erb" . html-erb-mode)
           (".erb" . html-erb-mode))
    :config
    (setq mmm-global-mode 'auto)
    (setq mmm-submode-decoration-level 2)
    (setq mmm-parse-when-idle t))
#+END_SRC

** Org-Mode
Include the org-habit module for the agenda:
#+BEGIN_SRC emacs-lisp
  (setq org-modules (quote (org-habit)))
#+END_SRC

*** Paths
This configuration assumes org files live in the =~/org= directory. You can
customize it by setting these variables in =../local/local.el=:
#+BEGIN_SRC emacs-lisp
  (setq org-directory "~/org")
  (setq org-default-notes-file "~/org/capture.org")
  (setq org-journal-file "~/org/journal.org.gpg")
  (setq org-work-journal-file "~/org/work.org")
  (setq org-log-file "~/org/log.org")
  (setq org-notes-file "~/org/notes.org")
  (setq org-archive-location "archive/%s_archive::")
  (setq org-agenda-files (filter (lambda (fn)
                                   (not (string-match (rx "#") fn)))
                                 (file-expand-wildcards org-directory)))
#+END_SRC

*** Capture Templates
Hit =C-c c= to trigger these:

#+BEGIN_SRC emacs-lisp
  (defun jm/find-org-headline (&optional heading)
    "Prompts for and finds a heading.

  Adapted from URL `http://emacs.stackexchange.com/a/5931'."
    (let* ((target (save-excursion
                     (org-refile-get-location heading nil t t)))
           (file (nth 1 target))
           (pos (nth 3 target)))
      (with-current-buffer (find-file-noselect org-notes-file)
        (goto-char pos)
        (org-end-of-subtree)
        (org-return))))

  (setq org-capture-templates
        '(("t" "TODO" entry (file+headline org-default-notes-file "Tasks")
           "* TODO %^{Task} %^g \n%U \n%?")
          ("w" "Work Journal" entry (file+datetree org-work-journal-file)
           "* %^{Title}\n%U \n%?\n")
          ("j" "Journal" entry (file+datetree org-journal-file)
           "* %^{Title}\n%U \n%?\n")
          ("n" "Notes" entry (file+function org-notes-file jm/find-org-headline)
           "* %^{Title}\n%U \n%?"
           :empty-lines 1)
          ("d" "Appointment" entry (file+headline org-default-notes-file "Tasks")
            "* TODO %^{Description} %^g\n%?\nSCHEDULED: %t\n%i\n%a")
          ("l" "Log" entry (file+datetree+prompt org-log-file)
           "* %^{Task} %^g\n%?" :clock-in t :clock-resume t)
          ))
#+END_SRC

*** Skeleton
#+BEGIN_SRC emacs-lisp
  (define-skeleton orgmode-skeleton
    "Inserts orgmode defaults into the current buffer."
    "Title: "
    "#+TITLE:       " str | (file-name-nondirectory buffer-file-name) \n
    "#+DESCRIPTION: " (skeleton-read "Description: ") \n
    "#+STARTUP:     align hidestars indent lognotedone" \n
    \n _)
#+END_SRC

*** Keybindings
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c l") 'org-store-link)
  (global-set-key (kbd "C-c a") 'org-agenda)
  (global-set-key (kbd "C-c c") 'org-capture)
  (global-set-key (kbd "C-c b") 'org-iswitchb)
  ;; for terminals -- TAB does not work
  (global-set-key (kbd "C-x t") 'org-cycle)
  (global-set-key (kbd "C-c C-x h") 'org-html-export-to-html)
#+END_SRC

*** Babel
Include these languages for babel
#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages (mapcar (lambda (l) (cons l t))
          '(C calc emacs-lisp gnuplot latex ledger perl python ruby screen sh)))
#+END_SRC

Highlight src blocks
#+BEGIN_SRC emacs-lisp
  (setq org-src-fontify-natively t)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (defun jm/org-confirm-babel-evaluate (lang body)
    "Don't ask to confirm evaluating a ledger block."
    (not (string= lang "ledger")))
  (setq org-confirm-babel-evaluate 'jm/org-confirm-babel-evaluate)
#+END_SRC

*** Diary/Agenda
Hide some holidays:
#+BEGIN_SRC emacs-lisp
  (setq holiday-bahai-holidays nil)
  (setq holiday-hebrew-holidays nil)
  (setq holiday-islamic-holidays nil)
#+END_SRC

Show the agenda from the current day:
#+BEGIN_SRC emacs-lisp
  (setq org-agenda-start-on-weekday nil)
#+END_SRC

Show all habits
#+BEGIN_SRC emacs-lisp
  (setq org-habit-show-habits-only-for-today nil)
#+END_SRC

Set the location for showing the sunrise/sunset in the agenda:
#+BEGIN_SRC emacs-lisp
  (setq calendar-latitude 47.9790)
  (setq calendar-longitude -122.2021)
  (setq calendar-location-name "Everett, WA")
#+END_SRC

*** Exporting
Remove "Valid XHTML" link
#+BEGIN_SRC emacs-lisp
  (setq org-export-html-validation-link nil)
#+END_SRC

Minted latex export
#+BEGIN_SRC emacs-lisp
  (setq org-export-latex-minted-options
        '(("fontsize" "\\scriptsize")))
#+END_SRC

** Perl
Use the more modern =cperl-mode=
#+BEGIN_SRC emacs-lisp
  (defalias 'perl-mode 'cperl-mode)
#+END_SRC

Use =cperl-mode= for =.t= tests
#+BEGIN_SRC emacs-lisp
  (associate-file-type '(".t") 'cperl-mode)
#+END_SRC

Use four-space indents
#+BEGIN_SRC emacs-lisp
  (setq cperl-indent-level 4)
#+END_SRC

Indent only four-spaces in broken-up calls like
#+BEGIN_SRC perl
  someCall(
      $var,
      $var2
  )
#+END_SRC
#+BEGIN_SRC emacs-lisp
  (setq cperl-indent-parens-as-block t)
  (setq cperl-close-paren-offset -4)
#+END_SRC

Fix indentation for lines not starting statements (e.g., hash members)
#+BEGIN_SRC emacs-lisp
  (setq cperl-continued-statement-offset 0)
#+END_SRC#+end_src

** R
#+BEGIN_SRC emacs-lisp
  (associate-file-type '(".R" ".r") 'r-mode)
  (autoload 'r-mode "ess-site" nil t)
#+END_SRC

Don't be so slow at evaluating buffers:
#+BEGIN_SRC emacs-lisp
  (setq ess-eval-visibly-p nil)
#+END_SRC

** Ruby
*** Running
Shortcut for running a script and returning focus to it:
#+BEGIN_SRC emacs-lisp
  (defun ruby-run-buffer ()
    "Run the current Ruby script and switch focus back to the script."
    (interactive)
    (ruby-compilation-this-buffer)
    (other-window -1))
#+END_SRC

*** Filetypes
#+BEGIN_SRC emacs-lisp
  (associate-file-type '(".rake" "Gemfile" "Rakefile" ".ru" "Capfile" "Guardfile") 'ruby-mode)
#+END_SRC

Turn on =rdoc-mode=:
#+BEGIN_SRC emacs-lisp
  (autoload 'rdoc-mode "rdoc-mode" "Major mode for rdoc files" t)
  (associate-file-type '(".rdoc" ".rd") 'rdoc-mode)
#+END_SRC

*** Hooks
#+BEGIN_SRC emacs-lisp
  (add-hook 'ruby-mode-hook
            (lambda ()
              (rspec-mode 1)
              ; for binding.pry to work -- hit C-x C-q at breakpoint
              (add-hook 'after-init-hook 'inf-ruby-switch-setup)
              (autoload 'ri "ri")
              (local-set-key (kbd "C-c , x") 'rspec-verify-single)
              (local-set-key (kbd "C-h r") 'yari)
              (local-set-key (kbd "C-c C-c") 'ruby-run-buffer)))
  (add-hook 'slim-mode-hook
            (lambda ()
              (local-set-key (kbd "C-c , r") 'rspec-rerun)))
#+END_SRC

*** RSpec
#+BEGIN_SRC emacs-lisp
  (setq rspec-use-rake-when-possible nil)
  (setq rspec-use-spring-when-possible t)
#+END_SRC

** Scheme
*** Variables
#+BEGIN_SRC emacs-lisp
  (setq scheme-program-name "scheme")
#+END_SRC

*** Helper functions
#+BEGIN_SRC emacs-lisp
  (defun scheme-run-buffer ()
    "Runs the current buffer through scheme and switches focus back to the script."
    (interactive)
    (scheme-send-region (point-min) (point-max)))
#+END_SRC

*** Hooks
#+BEGIN_SRC emacs-lisp
  (add-hook 'scheme-mode-hook
            (lambda ()
              (local-set-key (kbd "C-c C-c") 'scheme-run-buffer)
              (local-set-key (kbd "C-j") 'scheme-send-last-sexp)))
#+END_SRC

* Tools
** Browsers
There are far too many ways to configure which browser to use in emacs.
xdg-open should be the default but alas, we need this:

#+BEGIN_SRC emacs-lisp
  (setq shr-external-browser 'browse-url-xdg-open)
  (setq browse-url-browser-function 'browse-url-generic
        browse-url-generic-program "chromium-browser")
#+END_SRC

** Clock
Customize =M-x display-time-world=:
#+BEGIN_SRC emacs-lisp
(setq display-time-world-list
      '(("America/Los_Angeles" "Seattle")
        ("America/Denver" "Cascade")
        ("America/Chicago" "Ann Arbor")
        ("America/New_York" "New York")))
#+END_SRC

** Dired
Make it so hitting =C= on a filename in a dired window defaults to the
other dired window:

#+BEGIN_SRC emacs-lisp
  (setq dired-dwim-target t)
#+END_SRC

** Ledger
Add a few custom reports:
#+BEGIN_SRC emacs-lisp
  (use-package ledger-mode
    :defer t
    :config
    (setq ledger-reports
          '(
            ("taxes" "ledger -f %(ledger-file) bal --cleared Liabilities:Taxes Savings:Taxes")
            ("donations" "ledger -f %(ledger-file) bal Expenses:Donations Liabilities:Donations")
            ("biz-income" "ledger -f %(ledger-file) equity --cleared Revenue Biz:Receivable")
            ("biz-outstanding" "ledger -f %(ledger-file) reg Biz:Receivable")
            ("year-spending" "ledger -f %(ledger-file) --monthly --empty --collapse reg Expenses")
            ("uncleared" "ledger -f %(ledger-file) reg --uncleared")
            ("cc-spending" "ledger -f %(ledger-file) bal Liabilities:Credit -l 'amount < 0'")
            ("credit-cap1"
             "ledger -f %(ledger-file) reg Liabilities:Credit:CapitalOne --display 'd>=[last month]' --cleared")
            ("checking-cap1"
             "ledger -f %(ledger-file) reg Assets:Checking:CapitalOne --display 'd>=[last month]' --cleared")
            ("net" "ledger -f %(ledger-file) bal Assets Liabilities --cleared"))))
#+END_SRC

** Man
Open man pages in a different window
#+BEGIN_SRC emacs-lisp
  (setq Man-notify-method 'friendly)
#+END_SRC

I tend to keep man pages pretty narrow
#+BEGIN_SRC emacs-lisp
  (setenv "MANWIDTH" "72")
#+END_SRC

** Shell
Set =$PAGER= to =cat= to avoid =WARNING: terminal is not fully
functional= messages.
#+BEGIN_SRC emacs-lisp
  (setenv "PAGER" "cat")
#+END_SRC

Ensure eshell garbage stays in =~/.emacs.d/local=:
#+BEGIN_SRC emacs-lisp
  (setq eshell-directory-name (concat user-emacs-directory "local/eshell"))
#+END_SRC

** Silver Searcher
#+BEGIN_SRC emacs-lisp
(require 'ag)
(setq ag-highlight-search t)
#+END_SRC

* Local configuration
Load local config to override any of the above settings
#+BEGIN_SRC emacs-lisp
  (load (jm/local-path "local") 'noerror)
#+END_SRC
